// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyuexvpevpxmvghmfrrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5dWV4dnBldnB4bXZnaG1mcnJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNjQ5MTEsImV4cCI6MjA3NDc0MDkxMX0.brgtuRocDGoxqVuLi3aYHZI8k3LKYBsdppMIqaH1n58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});